import { createCipheriv, createDecipheriv, randomBytes, scryptSync } from 'node:crypto';
import { createErrorMessage } from '../../util/errors/ErrorUtil';
import type { KeyValueStorage } from './KeyValueStorage';
import { PassthroughKeyValueStorage } from './PassthroughKeyValueStorage';

// AES-256-GCM parameters.
const ALGORITHM = 'aes-256-gcm';
const KEY_LENGTH = 32;
const IV_LENGTH = 12;
// Fixed salt so the same secret always derives the same key across restarts,
// which is required to decrypt values written during previous runs.
const KEY_SALT = 'community-solid-server:storage-encryption:v1';

/**
 * The shape in which an {@link EncryptingKeyValueStorage} stores encrypted values in its source.
 *
 * The `encrypted` field acts as a marker: it allows legacy plaintext values,
 * written before encryption was enabled, to be distinguished from encrypted envelopes
 * so they can be returned unchanged.
 */
interface EncryptedEnvelope {
  encrypted: true;
  /** Base64-encoded initialization vector. */
  iv: string;
  /** Base64-encoded GCM authentication tag. */
  tag: string;
  /** Base64-encoded ciphertext of the JSON-serialized value. */
  value: string;
}

/**
 * Determines whether a stored value is an {@link EncryptedEnvelope} written by this storage,
 * as opposed to a legacy plaintext value that was written before encryption was enabled.
 *
 * @param value - The value retrieved from the source storage.
 */
function isEncryptedEnvelope(value: unknown): value is EncryptedEnvelope {
  return typeof value === 'object' && value !== null && (value as { encrypted?: unknown }).encrypted === true;
}

/**
 * A {@link KeyValueStorage} wrapper that transparently encrypts values at rest using AES-256-GCM.
 *
 * This is meant to protect sensitive internal secrets, such as the OIDC signing key generated by
 * `CachedJwkGenerator` and client-credential secrets, so that a leak of the underlying storage
 * (for example a backup or a path traversal) does not directly expose usable secrets.
 *
 * The wrapper is fully opt-in: it is only active when an operator explicitly wraps a source storage with it.
 * When active, it behaves transparently:
 * - `set` serializes the value, encrypts it with a random IV, and stores an {@link EncryptedEnvelope}.
 * - `get` decrypts an envelope back into the original value. If the stored value is *not* an envelope
 *   (a legacy plaintext value written before encryption was enabled), it is returned unchanged.
 *   This means existing deployments can enable encryption in place: old plaintext reads keep working,
 *   while every subsequent write is encrypted.
 * - `has` and `delete` operate on keys only and pass straight through.
 * - `entries` decrypts each value, transparently handling legacy plaintext entries as well.
 *
 * Keys are never encrypted or otherwise modified.
 *
 * The encryption key is derived with scrypt from an operator-provided secret passphrase,
 * passed as the `key` constructor argument. In the server configuration this is wired to the
 * `storageEncryptionKey` variable, which operators set through the `--storageEncryptionKey`
 * CLI argument or the `CSS_STORAGE_ENCRYPTION_KEY` environment variable. If the passphrase is
 * empty or absent, construction fails with a clear error rather than silently storing plaintext.
 *
 * WARNING: losing the secret makes every encrypted value permanently unrecoverable.
 */
export class EncryptingKeyValueStorage<TVal> extends PassthroughKeyValueStorage<TVal> {
  private readonly cryptoKey: Buffer;

  /**
   * @param source - The storage to wrap. Its values will hold encrypted envelopes.
   * @param key - The secret passphrase to derive the encryption key from.
   *              Wired to the `storageEncryptionKey` variable in the server configuration.
   */
  public constructor(source: KeyValueStorage<string, TVal>, key?: string) {
    super(source);
    if (typeof key !== 'string' || key.length === 0) {
      throw new Error(
        `Storage encryption is enabled but no encryption key was provided. Set the storageEncryptionKey ` +
        `variable through the --storageEncryptionKey CLI argument or the CSS_STORAGE_ENCRYPTION_KEY ` +
        `environment variable.`,
      );
    }
    this.cryptoKey = scryptSync(key, KEY_SALT, KEY_LENGTH);
  }

  public async get(key: string): Promise<TVal | undefined> {
    const stored = await this.valueSource.get(this.toNewKey(key));
    if (stored === undefined) {
      return undefined;
    }
    return this.decode(stored);
  }

  public async set(key: string, value: TVal): Promise<this> {
    await this.valueSource.set(this.toNewKey(key), this.encrypt(value));
    return this;
  }

  public async* entries(): AsyncIterableIterator<[string, TVal]> {
    for await (const [ key, stored ] of this.valueSource.entries()) {
      yield [ this.toOriginalKey(key), this.decode(stored) ];
    }
  }

  protected toNewKey(key: string): string {
    return key;
  }

  protected toOriginalKey(key: string): string {
    return key;
  }

  /**
   * A typed view of the wrapped storage. The source physically holds {@link EncryptedEnvelope} objects
   * (or legacy plaintext values), neither of which matches the `TVal` type exposed to callers.
   */
  private get valueSource(): KeyValueStorage<string, unknown> {
    return this.source as unknown as KeyValueStorage<string, unknown>;
  }

  /**
   * Converts a value read from the source back into the value exposed to callers,
   * decrypting encrypted envelopes and passing legacy plaintext values through unchanged.
   */
  private decode(stored: unknown): TVal {
    if (isEncryptedEnvelope(stored)) {
      return this.decrypt(stored);
    }
    // Legacy plaintext value written before encryption was enabled: return it unchanged.
    return stored as TVal;
  }

  /**
   * Encrypts a value into an {@link EncryptedEnvelope} using AES-256-GCM with a random IV.
   */
  private encrypt(value: TVal): EncryptedEnvelope {
    const iv = randomBytes(IV_LENGTH);
    const cipher = createCipheriv(ALGORITHM, this.cryptoKey, iv);
    const ciphertext = Buffer.concat([ cipher.update(JSON.stringify(value), 'utf-8'), cipher.final() ]);
    return {
      encrypted: true,
      iv: iv.toString('base64'),
      tag: cipher.getAuthTag().toString('base64'),
      value: ciphertext.toString('base64'),
    };
  }

  /**
   * Decrypts an {@link EncryptedEnvelope} back into the original value.
   * Throws a clear error if the key is incorrect or the data has been tampered with,
   * both of which cause GCM authentication to fail.
   */
  private decrypt(envelope: EncryptedEnvelope): TVal {
    try {
      const decipher = createDecipheriv(ALGORITHM, this.cryptoKey, Buffer.from(envelope.iv, 'base64'));
      decipher.setAuthTag(Buffer.from(envelope.tag, 'base64'));
      const plaintext = Buffer.concat([
        decipher.update(Buffer.from(envelope.value, 'base64')),
        decipher.final(),
      ]);
      return JSON.parse(plaintext.toString('utf-8')) as TVal;
    } catch (error: unknown) {
      throw new Error(
        `Unable to decrypt a stored value. The encryption passphrase may be incorrect ` +
        `or the stored data may be corrupted. ${createErrorMessage(error)}`,
      );
    }
  }
}
