import { getLoggerFor } from '../../../logging/LogUtil';
import { TooManyRequestsHttpError } from '../../../util/errors/TooManyRequestsHttpError';
import { SOLID_HTTP } from '../../../util/Vocabularies';
import type { JsonRepresentation } from '../InteractionUtil';
import type { JsonInteractionHandlerInput } from '../JsonInteractionHandler';
import { JsonInteractionHandler } from '../JsonInteractionHandler';
import type { JsonView } from '../JsonView';
import type { RateLimiter } from './RateLimiter';

export interface RateLimitHandlerArgs {
  /**
   * The handler that will be called when the request is within the rate limit.
   */
  source: JsonInteractionHandler & JsonView;
  /**
   * The rate limiter tracking the number of attempts for each key.
   * Handlers should not share a limiter so their limits are independent.
   */
  limiter: RateLimiter;
  /**
   * Whether rate limiting is enabled. Defaults to `true`.
   */
  enabled?: boolean;
  /**
   * If `true`, a successful action resets the counter for its key, so only failed attempts count.
   * Defaults to `false`, in which case every action counts.
   */
  resetOnSuccess?: boolean;
}

/**
 * Rate-limits the actions of the {@link JsonInteractionHandler} it wraps,
 * throwing a {@link TooManyRequestsHttpError} once the limit for a key is exceeded.
 * The key combines the client IP, read from the metadata generated by a {@link ClientIpParser},
 * with the `email` field of the body when one is present.
 * Views are returned unrestricted as only the actions are potential abuse vectors.
 */
export class RateLimitHandler extends JsonInteractionHandler implements JsonView {
  protected readonly logger = getLoggerFor(this);

  private readonly source: JsonInteractionHandler & JsonView;
  private readonly limiter: RateLimiter;
  private readonly enabled: boolean;
  private readonly resetOnSuccess: boolean;

  public constructor(args: RateLimitHandlerArgs) {
    super();
    this.source = args.source;
    this.limiter = args.limiter;
    this.enabled = args.enabled ?? true;
    this.resetOnSuccess = args.resetOnSuccess ?? false;
  }

  public async getView(input: JsonInteractionHandlerInput): Promise<JsonRepresentation> {
    return this.source.getView(input);
  }

  public async canHandle(input: JsonInteractionHandlerInput): Promise<void> {
    await this.source.canHandle(input);
  }

  public async handle(input: JsonInteractionHandlerInput): Promise<JsonRepresentation> {
    if (!this.enabled) {
      return this.source.handle(input);
    }

    const key = this.getKey(input);
    if (!this.limiter.isAllowed(key)) {
      this.logger.warn(`Rate limit exceeded for ${key}`);
      throw new TooManyRequestsHttpError('Too many requests, please try again later.');
    }

    let result: JsonRepresentation;
    try {
      result = await this.source.handle(input);
    } catch (error: unknown) {
      // Failed attempts always count towards the limit
      this.limiter.increment(key);
      throw error;
    }

    if (this.resetOnSuccess) {
      this.limiter.reset(key);
    } else {
      this.limiter.increment(key);
    }
    return result;
  }

  private getKey(input: JsonInteractionHandlerInput): string {
    const ip = input.metadata.get(SOLID_HTTP.terms.clientIp)?.value ?? 'unknown';
    const target = this.extractTarget(input.json);
    return target ? `${ip}:${target}` : ip;
  }

  private extractTarget(json: unknown): string | undefined {
    if (typeof json !== 'object' || json === null) {
      return undefined;
    }
    const value = (json as Record<string, unknown>).email;
    if (typeof value === 'string' && value.length > 0) {
      // Emails are case-insensitive
      return value.toLowerCase();
    }
    return undefined;
  }
}
