import { DataFactory } from 'n3';
import { BasicRepresentation } from '../../../../../src/http/representation/BasicRepresentation';
import { RepresentationMetadata } from '../../../../../src/http/representation/RepresentationMetadata';
import type { ResourceIdentifier } from '../../../../../src/http/representation/ResourceIdentifier';
import {
  deserializeMetadata,
  serializeMetadata,
} from '../../../../../src/server/notifications/cluster/ClusterActivityUtil';
import {
  AddRemoveNotificationGenerator,
} from '../../../../../src/server/notifications/generate/AddRemoveNotificationGenerator';
import type { NotificationChannel } from '../../../../../src/server/notifications/NotificationChannel';
import { BasicETagHandler } from '../../../../../src/storage/conditions/BasicETagHandler';
import type { ETagHandler } from '../../../../../src/storage/conditions/ETagHandler';
import type { ResourceStore } from '../../../../../src/storage/ResourceStore';
import { ContentType } from '../../../../../src/util/Header';
import { AS, CONTENT_TYPE, DC, LDP, RDF, SOLID_AS, SOLID_META, XSD } from '../../../../../src/util/Vocabularies';

const { blankNode, literal, namedNode } = DataFactory;

/**
 * Serializes and deserializes the given metadata,
 * with a `structuredClone` in between to simulate crossing a process boundary.
 */
async function roundTrip(metadata: RepresentationMetadata): Promise<RepresentationMetadata> {
  const serialized = await serializeMetadata(metadata);
  return deserializeMetadata(structuredClone(serialized));
}

describe('ClusterActivityUtil', (): void => {
  const topic: ResourceIdentifier = { path: 'http://example.com/container/' };
  const object: ResourceIdentifier = { path: 'http://example.com/container/resource' };

  it('preserves the identifier and solid:activity term of resource change metadata.', async(): Promise<void> => {
    // The metadata shape generated by `DataAccessorBasedStore` for Create/Update/Delete activities
    const metadata = new RepresentationMetadata(object, { [SOLID_AS.activity]: AS.terms.Update });

    const result = await roundTrip(metadata);
    expect(result.identifier).toEqualRdfTerm(namedNode(object.path));
    expect(result.get(SOLID_AS.terms.activity)).toEqualRdfTerm(AS.terms.Update);
    expect(result.quads()).toBeRdfIsomorphic(metadata.quads());
  });

  it('preserves blank node identifiers and as:object of Add/Remove metadata.', async(): Promise<void> => {
    // The metadata shape of `DataAccessorBasedStore.addContainerActivity`
    const metadata = new RepresentationMetadata({
      [SOLID_AS.activity]: AS.terms.Add,
      [AS.object]: namedNode(object.path),
    });

    const result = await roundTrip(metadata);
    expect(result.identifier.termType).toBe('BlankNode');
    expect(result.identifier).toEqualRdfTerm(metadata.identifier);
    expect(result.get(SOLID_AS.terms.activity)).toEqualRdfTerm(AS.terms.Add);
    expect(result.getAll(AS.terms.object)).toEqualRdfTermArray([ namedNode(object.path) ]);
    expect(result.quads()).toBeRdfIsomorphic(metadata.quads());
  });

  it('lets round-tripped metadata drive the AddRemoveNotificationGenerator.', async(): Promise<void> => {
    const metadata = new RepresentationMetadata({
      [SOLID_AS.activity]: AS.terms.Add,
      [AS.object]: namedNode(object.path),
    });
    const channel: NotificationChannel = { id: 'id', topic: topic.path, type: 'type' };
    const responseMetadata = new RepresentationMetadata(topic, {
      [DC.modified]: new Date().toISOString(),
      [CONTENT_TYPE]: 'text/turtle',
    });
    const store: jest.Mocked<ResourceStore> = {
      getRepresentation: jest.fn().mockResolvedValue(new BasicRepresentation('', responseMetadata)),
    } as any;
    const eTagHandler: jest.Mocked<ETagHandler> = {
      getETag: jest.fn().mockReturnValue('"123456-text/turtle"'),
      matchesETag: jest.fn(),
      sameResourceState: jest.fn(),
    };
    const generator = new AddRemoveNotificationGenerator(store, eTagHandler);

    const notification = await generator
      .handle({ topic, channel, activity: AS.terms.Add, metadata: await roundTrip(metadata) });
    expect(notification.type).toBe('Add');
    expect(notification.object).toBe(object.path);
    expect(notification.target).toBe(topic.path);
  });

  it('preserves the fields used to generate ETags.', async(): Promise<void> => {
    const eTagHandler = new BasicETagHandler();
    const metadata = new RepresentationMetadata(object, {
      [DC.modified]: new Date().toISOString(),
      [CONTENT_TYPE]: 'text/turtle',
    });
    const eTag = eTagHandler.getETag(metadata);
    expect(eTag).toBeDefined();

    const result = await roundTrip(metadata);
    expect(eTagHandler.getETag(result)).toBe(eTag);
    expect(eTagHandler.matchesETag(result, eTag!, true)).toBe(true);
  });

  it('preserves content type parameters.', async(): Promise<void> => {
    const metadata = new RepresentationMetadata(object);
    metadata.contentTypeObject = new ContentType('text/plain', { charset: 'utf-8' });

    const result = await roundTrip(metadata);
    expect(result.contentType).toBe('text/plain');
    expect(result.contentTypeObject?.parameters).toEqual({ charset: 'utf-8' });
  });

  it('preserves typed literals, language literals, and special characters.', async(): Promise<void> => {
    const metadata = new RepresentationMetadata(object);
    metadata.add(namedNode('urn:example:int'), literal('5', XSD.terms.integer));
    metadata.add(namedNode('urn:example:lang'), literal('hallo', 'nl'));
    metadata.add(namedNode('urn:example:text'), literal('line1\nline2 "quoted" \\slashed'));

    const result = await roundTrip(metadata);
    expect(result.get(namedNode('urn:example:int'))).toEqualRdfTerm(literal('5', XSD.terms.integer));
    expect(result.get(namedNode('urn:example:lang'))).toEqualRdfTerm(literal('hallo', 'nl'));
    expect(result.get(namedNode('urn:example:text'))).toEqualRdfTerm(literal('line1\nline2 "quoted" \\slashed'));
  });

  it('preserves quads in named graphs.', async(): Promise<void> => {
    const metadata = new RepresentationMetadata(object);
    metadata.add(RDF.terms.type, LDP.terms.Resource, SOLID_META.terms.ResponseMetadata);

    const result = await roundTrip(metadata);
    expect(result.quads(null, RDF.terms.type, null, SOLID_META.terms.ResponseMetadata)).toHaveLength(1);
    expect(result.getAll(RDF.terms.type, SOLID_META.terms.ResponseMetadata))
      .toEqualRdfTermArray([ LDP.terms.Resource ]);
  });

  it('round-trips metadata without any quads.', async(): Promise<void> => {
    const metadata = new RepresentationMetadata();

    const result = await roundTrip(metadata);
    expect(result.identifier).toEqualRdfTerm(metadata.identifier);
    expect(result.quads()).toHaveLength(0);
  });

  it('deserializes blank node identifiers that were not generated by this process.', async(): Promise<void> => {
    const result = await deserializeMetadata({
      identifier: { termType: 'BlankNode', value: 'remote' },
      quads: `_:remote <${AS.object}> <${object.path}> .\n`,
    });
    expect(result.identifier).toEqualRdfTerm(blankNode('remote'));
    expect(result.getAll(AS.terms.object)).toEqualRdfTermArray([ namedNode(object.path) ]);
  });
});
